---
- name: Install Prometheus
  hosts: monitor
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - prometheus.prometheus.prometheus
  vars:
    prometheus_scrape_configs:
      - job_name: "webserver"
        static_configs:
          - targets: ["10.0.0.5:9100"]
