---
- name: Install Node Exporter via Ansible Galaxy role
  hosts:
    - web
    - monitor
    - controller
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - prometheus.prometheus.node_exporter
